### ISSUE TITLE
Working with Isomorphic Apps

### ISSUE THREAD

**Issue by casoetan** [Stanko/react-plx#6]
Any thoughts on this...

```bash
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/me/template/node_modules/react-plx/lib/scroll-manager.js:17:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/template/node_modules/react-plx/lib/Plx.js:25:22)
    at Module._compile (module.js:573:30)
```

**Comment by Stanko** [comment]
Hello @casoetan,
Quick fix would be to inject environment variable `SERVER_RENDER` into `process.env.SERVER_RENDER` using https://webpack.js.org/plugins/define-plugin/, and then don't render this component if it is `true`.

But I will add a prop in the version which will be called `serverRender` or `moveWindowStuffToComponentDidMount` 🙂 which will move adding window event listeners to `componentDidMount`. Atm these are created in the `constructor` and `componentWillMount`.

Cheers!

**Comment by Stanko** [comment]
@casoetan I just released version with the fix for universal rendering. Could you please try with this version and close the issue if it is resolved.

commit: https://github.com/Stanko/react-plx/commit/31d15ca70af62011bc02d75e4907255d5b45feba

**Comment by casoetan** [comment]
@Stanko works great now.

Best,

**Comment by Stanko** [comment]
Glad it helped!

P.S. If you can share, I would really like to see where are you using Plx :)

**Comment by casoetan** [comment]
Working offline. Will definitely share as soon as I can.

Best, \Charles
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.55&pv=10.12.6&source=email_footer_2]
On Thu, Aug 31, 2017 at 11:29, Stanko <notifications@github.com> wrote:
Glad it helped!

P.S. If you can share, I would really like to see where are you using Plx :)
